/**
 * Vitest globalSetup — runs ONCE before the test suite.
 *
 * Recreates the test database from scratch and loads the schema
 * snapshot (apps/api/src/db/schema.sql, regenerated by the migration
 * runner). Schema-only — no seeded data; individual tests insert
 * whatever rows they need.
 *
 * The test DB name is controlled by TEST_DB_NAME (default 'gam_test').
 * Forced to a *_test suffix as a guard against accidentally pointing
 * tests at the dev DB.
 *
 * Connection creds are read from the same env vars the API uses
 * (DB_HOST/DB_PORT/DB_USER/DB_PASSWORD), with dotenv loading the
 * apps/api/.env file if those vars aren't already set in the
 * environment.
 */

import dotenv from 'dotenv'
import fs from 'fs'
import path from 'path'
import { Client } from 'pg'

dotenv.config({ path: path.join(__dirname, '..', '..', '.env') })

const TEST_DB_NAME = process.env.TEST_DB_NAME || 'gam_test'

if (!TEST_DB_NAME.endsWith('_test')) {
  throw new Error(
    `Refusing to use '${TEST_DB_NAME}' as test database — name must end with '_test'`
  )
}

const PG_CONFIG = {
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
}

const SCHEMA_PATH = path.join(__dirname, '..', 'db', 'schema.sql')

export async function setup(): Promise<void> {
  if (!fs.existsSync(SCHEMA_PATH)) {
    throw new Error(`schema.sql not found at ${SCHEMA_PATH} — run npm run db:dump-schema`)
  }
  // pg_dump 16+ emits psql meta-commands (\restrict / \unrestrict) at the
  // start and end of the dump. These aren't valid SQL and the node pg
  // driver chokes on them — strip any line beginning with backslash before
  // sending to the server.
  const schemaSql = fs.readFileSync(SCHEMA_PATH, 'utf8')
    .split('\n')
    .filter(line => !line.startsWith('\\'))
    .join('\n')

  const admin = new Client({ ...PG_CONFIG, database: 'postgres' })
  await admin.connect()
  try {
    await admin.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [TEST_DB_NAME]
    )
    await admin.query(`DROP DATABASE IF EXISTS ${TEST_DB_NAME}`)
    await admin.query(`CREATE DATABASE ${TEST_DB_NAME}`)
  } finally {
    await admin.end()
  }

  const target = new Client({ ...PG_CONFIG, database: TEST_DB_NAME })
  await target.connect()
  try {
    await target.query(schemaSql)
  } finally {
    await target.end()
  }

  process.env.DB_NAME = TEST_DB_NAME

  // Best-effort propagation to workers — vitest reads process.env when forking.
  // Worker processes also receive env via the parent's process.env at fork time,
  // so setting it here before workers spawn is sufficient.
}

export async function teardown(): Promise<void> {
  // Intentionally leave the test DB in place for post-run inspection.
  // The next run drops + recreates it. No cleanup needed.
}
