/**
 * Vitest globalSetup — runs ONCE before the test suite.
 *
 * Recreates the test database from scratch and loads the schema
 * snapshot (apps/api/src/db/schema.sql, regenerated by the migration
 * runner). Schema-only — no seeded data; individual tests insert
 * whatever rows they need.
 *
 * The test DB name is controlled by TEST_DB_NAME (default 'gam_test').
 * Forced to a *_test suffix as a guard against accidentally pointing
 * tests at the dev DB.
 *
 * Connection creds are read from the same env vars the API uses
 * (DB_HOST/DB_PORT/DB_USER/DB_PASSWORD), with dotenv loading the
 * apps/api/.env file if those vars aren't already set in the
 * environment.
 */

import dotenv from 'dotenv'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { Client } from 'pg'

dotenv.config({ path: path.join(__dirname, '..', '..', '.env') })

const TEST_DB_NAME = process.env.TEST_DB_NAME || 'gam_test'

if (!TEST_DB_NAME.endsWith('_test')) {
  throw new Error(
    `Refusing to use '${TEST_DB_NAME}' as test database — name must end with '_test'`
  )
}

const PG_CONFIG = {
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
}

const SCHEMA_PATH = path.join(__dirname, '..', 'db', 'schema.sql')

/**
 * S628 — REFUSE TO START IF ANOTHER RUN IS ALREADY GOING.
 *
 * This setup DROPs and recreates the test database. A second vitest therefore
 * pulls the database out from under the first, and what comes back is not an
 * obvious error — it is a scatter of file-level load failures across unrelated
 * suites that reads exactly like a real regression. It cost an hour in S626
 * (224 phantom failures) and twice more on 2026-08-28: once diagnosing a
 * foreign-key violation inside an agent tool that did not exist, and once
 * reading 175 failures across six files as a regression in work that was fine.
 *
 * The handoff has said "never run two at once" since S626 and I did it anyway,
 * twice in a day, because the fast agents-only loop (~4 s) does not feel like
 * "a run" when a 30-minute suite is in the background. A note in a document
 * cannot fix that. A lock can.
 *
 * The lock is a PID file, and it is checked for liveness rather than trusted —
 * a killed run must not leave the suite unrunnable, which would be a worse
 * failure than the one being prevented. Set VITEST_ALLOW_CONCURRENT=1 to
 * override deliberately.
 */
const LOCK_PATH = path.join(os.tmpdir(), `gam-vitest-${TEST_DB_NAME}.lock`)

function alive(pid: number): boolean {
  try { process.kill(pid, 0); return true } catch { return false }
}

function claimLock(): void {
  if (process.env.VITEST_ALLOW_CONCURRENT === '1') return
  try {
    const existing = Number(fs.readFileSync(LOCK_PATH, 'utf8').trim())
    if (Number.isFinite(existing) && existing !== process.pid && alive(existing)) {
      throw new Error(
        `\n\n  ANOTHER VITEST RUN IS ALREADY GOING (pid ${existing}).\n\n` +
        `  Starting this one would DROP and recreate ${TEST_DB_NAME} underneath it, and the\n` +
        '  result is file-level failures scattered across unrelated suites that read like a\n' +
        '  real regression. Wait for it, or kill it:\n\n' +
        `      ps aux | grep [v]itest\n\n` +
        '  If you are certain nothing else is running, remove the lock:\n\n' +
        `      rm ${LOCK_PATH}\n`,
      )
    }
  } catch (e: any) {
    // A missing or unreadable lock file is the normal case; only re-throw the
    // refusal above.
    if (e?.message?.includes('ANOTHER VITEST RUN')) throw e
  }
  fs.writeFileSync(LOCK_PATH, String(process.pid))
}

export async function setup(): Promise<void> {
  claimLock()
  if (!fs.existsSync(SCHEMA_PATH)) {
    throw new Error(`schema.sql not found at ${SCHEMA_PATH} — run npm run db:dump-schema`)
  }
  // pg_dump 16+ emits psql meta-commands (\restrict / \unrestrict) at the
  // start and end of the dump. These aren't valid SQL and the node pg
  // driver chokes on them — strip any line beginning with backslash before
  // sending to the server.
  const schemaSql = fs.readFileSync(SCHEMA_PATH, 'utf8')
    .split('\n')
    .filter(line => !line.startsWith('\\'))
    .join('\n')

  const admin = new Client({ ...PG_CONFIG, database: 'postgres' })
  await admin.connect()
  try {
    await admin.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [TEST_DB_NAME]
    )
    await admin.query(`DROP DATABASE IF EXISTS ${TEST_DB_NAME}`)
    await admin.query(`CREATE DATABASE ${TEST_DB_NAME}`)
  } finally {
    await admin.end()
  }

  const target = new Client({ ...PG_CONFIG, database: TEST_DB_NAME })
  await target.connect()
  try {
    await target.query(schemaSql)
  } finally {
    await target.end()
  }

  process.env.DB_NAME = TEST_DB_NAME

  // Best-effort propagation to workers — vitest reads process.env when forking.
  // Worker processes also receive env via the parent's process.env at fork time,
  // so setting it here before workers spawn is sufficient.
}

export async function teardown(): Promise<void> {
  // Intentionally leave the test DB in place for post-run inspection.
  // The next run drops + recreates it. No cleanup needed.
  //
  // The lock DOES go, so a finished run never blocks the next one. Only this
  // process's own lock — a crashed run leaves a stale file, and the liveness
  // check in claimLock is what makes that harmless.
  try {
    if (Number(fs.readFileSync(LOCK_PATH, 'utf8').trim()) === process.pid) fs.unlinkSync(LOCK_PATH)
  } catch { /* nothing to release */ }
}
