/**
 * Seed-migration generator for the S442 state-law KB.
 *
 * Turns a verified research batch (the JSON result of the
 * state-law-research-batch workflow) into a seed migration: acts +
 * residential provisions, with template plain-language summaries, the
 * official citations/URLs, and each state's sourcing notes preserved as SQL
 * comments. Provisions attach to each state's 'residential' act; a topic with
 * no statutory value is simply absent (never invented).
 *
 * Usage: node -r ts-node/register src/db/genStateLawSeed.ts <batch.json> <out.sql> [YYYY-MM-DD]
 */

import * as fs from 'fs'

const inPath = process.argv[2]
const outPath = process.argv[3]
const SOURCE_DATE = process.argv[4] || '2026-06-11'
const EFFECTIVE_YEAR = Number((SOURCE_DATE.match(/^(\d{4})/) || [])[1]) || 2026

const raw = JSON.parse(fs.readFileSync(inPath, 'utf8'))
const states: any[] = raw.result?.states || raw.states || []

const dec = (s: any) => String(s ?? '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'").replace(/&quot;/g, '"')
const q = (s: any) => String(s ?? '').replace(/'/g, "''")
const arr = (a: string[]) => 'ARRAY[' + (a || []).map((x) => `'${q(x)}'`).join(',') + ']::text[]'

// Each topic's CANONICAL unit (what check_against_law compares in) + scale.
const CANON: Record<string, { unit: string; scale: string }> = {
  entry_notice_hours: { unit: 'hours', scale: 'hours' },
  deposit_max_months: { unit: 'months of rent', scale: 'months' },
  deposit_return_days: { unit: 'days', scale: 'days' },
  late_fee_max_pct: { unit: '% of rent', scale: 'pct' },
  late_fee_grace_days: { unit: 'days', scale: 'days' },
  notice_to_vacate_days: { unit: 'days', scale: 'days' },
}

// Convert a researched value into the topic's canonical unit, inferring the
// source scale from its unit string (e.g. "1 month" notice → 30 days). The
// research agents return values in the statute's native unit, which doesn't
// always match the canonical one — this makes the numeric comparison correct.
function canonValue(topic: string, value: any, unit: any) {
  const scale = CANON[topic]?.scale
  const u = String(unit ?? '').toLowerCase()
  let v = Number(value)
  let converted = false, orig = ''
  if (scale === 'days') {
    if (u.includes('month')) { orig = `${value} month${value == 1 ? '' : 's'}`; v = Math.round(v * 30); converted = true }
    else if (u.includes('week')) { orig = `${value} week${value == 1 ? '' : 's'}`; v = v * 7; converted = true }
  } else if (scale === 'hours') {
    if (u.includes('day')) { orig = `${value} day${value == 1 ? '' : 's'}`; v = v * 24; converted = true }
  }
  return { value: v, converted, orig, businessDays: scale === 'days' && u.includes('business') }
}

function summary(topic: string, cv: { value: number; converted: boolean; orig: string; businessDays: boolean }): string {
  const v = cv.value
  const note = cv.converted ? ` (statute states ${cv.orig})` : ''
  const bd = cv.businessDays ? 'business ' : ''
  switch (topic) {
    case 'entry_notice_hours': return `At least ${v} hours' advance notice is generally required before the landlord enters${note}.`
    case 'deposit_max_months': return `A security deposit may not exceed ${v} month${v == 1 ? '' : 's'} of rent.`
    case 'deposit_return_days': return `The deposit must be returned within ${v} days after the tenancy ends${note}.`
    case 'late_fee_max_pct': return `A late fee may not exceed ${v}% of the rent.`
    case 'late_fee_grace_days': return `A late fee may not be charged until at least ${v} ${bd}days after rent is due.`
    case 'notice_to_vacate_days': return `Ending a month-to-month tenancy generally requires at least ${v} days' notice${note}.`
    default: return `${topic}: ${v}.`
  }
}

let out = `-- State landlord/tenant law seed — batch (generated by genStateLawSeed.ts).\n`
out += `-- Sourced from official .gov statutes ${SOURCE_DATE}; every value cited + independently verified\n`
out += `-- against the quoted statute text before seeding. Provisions attach to each state's 'residential'\n`
out += `-- act; a topic absent for a state = no statutory value exists (NOT invented). Hedged + dated +\n`
out += `-- disclaimered at surface time per the S442 posture. States: ${states.map((s) => s.code).join(', ')}.\n--\n`
out += `-- SOURCING NOTES (nuances the figures alone don't capture — read before relying on a value):\n`
for (const s of states) {
  if (!s.notes) continue
  for (const line of dec(s.notes).split('\n').map((l: string) => l.trim()).filter(Boolean)) {
    out += `-- [${s.code}] ${line}\n`
  }
  out += '--\n'
}

// ── Acts ──
out += `\nINSERT INTO public.state_landlord_tenant_acts\n  (state_code, act_key, act_name, unit_types, official_url, summary, source_date, effective_year)\nVALUES\n`
const actRows: string[] = []
for (const s of states) for (const a of s.acts || []) {
  actRows.push(`  ('${q(s.code)}', '${q(a.actKey)}', '${q(dec(a.actName))}', ${arr(a.unitTypes)}, '${q(dec(a.officialUrl))}', '${q(dec(a.citation))}', DATE '${SOURCE_DATE}', ${EFFECTIVE_YEAR})`)
}
out += actRows.join(',\n') + ';\n'

// ── Provisions (per state, attached to the 'residential' act) ──
let provCount = 0
for (const s of states) {
  const provs = (s.provisions || []).filter((p: any) => p.topic && p.value != null)
  if (!provs.length) continue
  provCount += provs.length
  out += `\nINSERT INTO public.state_law_provisions\n  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)\n`
  out += `SELECT a.id, '${q(s.code)}', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '${SOURCE_DATE}', ${EFFECTIVE_YEAR}\n`
  out += `FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES\n`
  out += provs.map((p: any) => {
    const cv = canonValue(p.topic, p.value, p.unit)
    const dispUnit = cv.businessDays ? 'business days' : (CANON[p.topic]?.unit ?? p.unit)
    if (cv.converted) console.log(`  [${s.code}] converted ${p.topic}: ${cv.orig} → ${cv.value} ${dispUnit}`)
    return `  ('${q(p.topic)}', '${q(p.ruleKind)}', ${cv.value}::numeric, '${q(dispUnit)}', '${q(summary(p.topic, cv))}', '${q(dec(p.citation))}', '${q(dec(p.sourceUrl))}')`
  }).join(',\n')
  out += `\n) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)\n`
  out += `WHERE a.state_code = '${q(s.code)}' AND a.act_key = 'residential' AND a.effective_year = ${EFFECTIVE_YEAR};\n`
}

fs.writeFileSync(outPath, out)
console.log(`wrote ${outPath}: ${actRows.length} acts, ${provCount} provisions across ${states.length} states (${states.map((s) => s.code).join(',')})`)
