/**
 * S473 — stale-route cleanup cron coverage.
 */

import { describe, it, expect, beforeEach } from 'vitest'
import { randomUUID } from 'crypto'
import bcrypt from 'bcryptjs'
import { db } from '../db'
import { cleanupAllSchema } from '../test/dbHelpers'
import { processRouteCleanup } from './routeCleanup'

beforeEach(async () => {
  await cleanupAllSchema()
})

interface Fixture {
  businessId: string
  depotId: string
  vehicleId: string
}

async function seedFixture(): Promise<Fixture> {
  const hash = await bcrypt.hash('super-strong-password-12!', 12)
  const email = `o-${randomUUID()}@example.com`
  const { rows: [u] } = await db.query<{ id: string }>(
    `INSERT INTO users (email, password_hash, role, first_name, last_name, email_verified)
     VALUES ($1, $2, 'business_owner', 'B', 'O', TRUE) RETURNING id`,
    [email, hash])
  const { rows: [b] } = await db.query<{ id: string }>(
    `INSERT INTO businesses (owner_user_id, name, business_type, email)
     VALUES ($1, 'Hauling Co', 'trash_hauling', $2) RETURNING id`,
    [u.id, email])
  const { rows: [d] } = await db.query<{ id: string }>(
    `INSERT INTO depots (business_id, name, street1, city, state, zip, lat, lon)
     VALUES ($1, 'Main Yard', '1 Yard', 'Phoenix', 'AZ', '85001', 33.4, -112.0)
     RETURNING id`, [b.id])
  const { rows: [v] } = await db.query<{ id: string }>(
    `INSERT INTO vehicles (business_id, home_depot_id, name)
     VALUES ($1, $2, 'Truck 1') RETURNING id`, [b.id, d.id])
  return { businessId: b.id, depotId: d.id, vehicleId: v.id }
}

async function seedRoute(args: {
  fx: Fixture
  date: string      // YYYY-MM-DD
  status: 'generated' | 'in_progress' | 'completed'
  withStopCount?: number
}): Promise<string> {
  // started_at / completed_at required for non-generated by the audit
  // CHECK; default to 6am Phoenix for the date.
  const startedAt = args.status !== 'generated' ? `${args.date}T13:00:00Z` : null
  const completedAt = args.status === 'completed' ? `${args.date}T18:00:00Z` : null
  const { rows: [r] } = await db.query<{ id: string }>(
    `INSERT INTO generated_routes
       (business_id, vehicle_id, depot_id, generated_for_date,
        start_at_planned, status, started_at, completed_at,
        total_miles, total_minutes, stop_count, dump_count)
     VALUES ($1, $2, $3, $4::date, ($4 || 'T09:00:00Z')::timestamptz,
             $5, $6::timestamptz, $7::timestamptz,
             10.5, 90, 5, 1)
     RETURNING id`,
    [args.fx.businessId, args.fx.vehicleId, args.fx.depotId,
     args.date, args.status, startedAt, completedAt])
  // Add a depot_return stop so the cascade has something to delete.
  const n = args.withStopCount ?? 0
  for (let i = 0; i < n; i++) {
    await db.query(
      `INSERT INTO route_stops
         (route_id, sequence_order, stop_kind,
          estimated_arrival, estimated_departure)
       VALUES ($1, $2, 'depot_return',
               ($3 || 'T09:00:00Z')::timestamptz,
               ($3 || 'T09:30:00Z')::timestamptz)`,
      [r.id, i + 1, args.date])
  }
  return r.id
}

describe('processRouteCleanup', () => {
  it('deletes a stale generated route + cascades its stops', async () => {
    const fx = await seedFixture()
    const oldDate = new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString().slice(0, 10)
    const id = await seedRoute({ fx, date: oldDate, status: 'generated', withStopCount: 3 })

    const result = await processRouteCleanup()
    expect(result.routes_deleted).toBe(1)
    expect(result.stops_deleted).toBe(3)
    const { rowCount } = await db.query(`SELECT 1 FROM generated_routes WHERE id=$1`, [id])
    expect(rowCount).toBe(0)
  })

  it('keeps a generated route inside the retention window', async () => {
    const fx = await seedFixture()
    // 3 days old — well within the 7-day window.
    const recent = new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString().slice(0, 10)
    const id = await seedRoute({ fx, date: recent, status: 'generated' })
    const result = await processRouteCleanup()
    expect(result.routes_deleted).toBe(0)
    const { rowCount } = await db.query(`SELECT 1 FROM generated_routes WHERE id=$1`, [id])
    expect(rowCount).toBe(1)
  })

  it('NEVER deletes in_progress or completed routes regardless of age', async () => {
    const fx = await seedFixture()
    const veryOld = new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString().slice(0, 10)
    const inProg = await seedRoute({ fx, date: veryOld, status: 'in_progress' })
    const done   = await seedRoute({ fx, date: veryOld, status: 'completed' })
    const result = await processRouteCleanup()
    expect(result.routes_deleted).toBe(0)
    const { rowCount: rc1 } = await db.query(`SELECT 1 FROM generated_routes WHERE id=$1`, [inProg])
    const { rowCount: rc2 } = await db.query(`SELECT 1 FROM generated_routes WHERE id=$1`, [done])
    expect(rc1).toBe(1)
    expect(rc2).toBe(1)
  })

  it('configurable retention: 30-day window skips a 10-day-old route', async () => {
    const fx = await seedFixture()
    const tenDaysOld = new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString().slice(0, 10)
    await seedRoute({ fx, date: tenDaysOld, status: 'generated' })
    const result = await processRouteCleanup(30)
    expect(result.routes_deleted).toBe(0)
  })

  it('idempotent: second run is a no-op', async () => {
    const fx = await seedFixture()
    const oldDate = new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString().slice(0, 10)
    await seedRoute({ fx, date: oldDate, status: 'generated' })
    await processRouteCleanup()
    const result = await processRouteCleanup()
    expect(result.routes_deleted).toBe(0)
    expect(result.stops_deleted).toBe(0)
  })

  it('no rows at all → 0/0', async () => {
    await seedFixture()
    const result = await processRouteCleanup()
    expect(result).toEqual({ routes_deleted: 0, stops_deleted: 0 })
  })
})
