#!/bin/bash
# Regenerates apps/api/src/db/schema.sql from the live database as a
# human-readable reference snapshot. Not source of truth — see banner
# in the generated file.
set -e

DEST="apps/api/src/db/schema.sql"
TODAY=$(date -u +%Y-%m-%d)
TMPDUMP=$(mktemp)

pg_dump -h localhost -p 5432 -U postgres -d gam \
  --schema-only --no-owner --no-privileges --no-comments \
  > "$TMPDUMP"

# Strip psql meta-commands (\restrict / \unrestrict) that pg_dump 16+
# emits but node-pg cannot parse.
python3 - "$TMPDUMP" <<'PYEOF'
import sys
from pathlib import Path
p = Path(sys.argv[1])
lines = p.read_text().splitlines()
filtered = [ln for ln in lines if not ln.startswith(r'\restrict') and not ln.startswith(r'\unrestrict')]
p.write_text('\n'.join(filtered) + '\n')
PYEOF

cat > "$DEST" <<HEADEREOF
-- ============================================================
-- GAM DATABASE SCHEMA — GENERATED REFERENCE FILE
-- ============================================================
--
-- DO NOT EDIT THIS FILE.
--
-- This is a snapshot of the live database schema, regenerated
-- from pg_dump. It exists as a human-readable overview only.
--
-- The source of truth for schema changes is the migrations
-- directory: apps/api/src/db/migrations/
--
-- To make a schema change:
--   1. Write a new timestamped migration file in migrations/
--   2. Run \`npm run db:migrate\` (or boot dev.sh, which runs it).
--   3. Regenerate this file with \`npm run schema:dump\`.
--
-- This file is not executed by any tool. The runner ignores it.
-- Editing it has no effect on the database.
--
-- Last regenerated: ${TODAY}
-- Source DB: gam @ localhost:5432
-- ============================================================

HEADEREOF

cat "$TMPDUMP" >> "$DEST"
rm "$TMPDUMP"
echo "schema.sql regenerated ($(wc -l < "$DEST") lines)."
