-- State landlord/tenant law seed — batch (generated by genStateLawSeed.ts).
-- Sourced from official .gov statutes 2026-06-11; every value cited + independently verified
-- against the quoted statute text before seeding. Provisions attach to each state's 'residential'
-- act; a topic absent for a state = no statutory value exists (NOT invented). Hedged + dated +
-- disclaimered at surface time per the S442 posture. States: NH, ME, RI, MT, DE, SD, ND, AK, VT, WY.
--
-- SOURCING NOTES (nuances the figures alone don't capture — read before relying on a value):
-- [NH] OFFICIAL SOURCE: New Hampshire General Court statutes, formerly at gencourt.state.nh.us, now permanently redirected (301) to gc.nh.gov. All URLs use the live gc.nh.gov host.
-- [NH] ACTS / UNIT-TYPE MAPPING:
-- [NH] - Residential dwellings (apartment, single_family) are governed by the pairing of RSA 540 (Actions Against Tenants — eviction, notice to quit, grounds) and RSA 540-A (Prohibited Practices and Security Deposits). These two chapters together form the residential landlord-tenant act; NH has no single consolidated "residential tenancy act." Security-deposit rules in RSA 540-A:5-8 carry some exemptions (e.g., certain single-family owner-occupant arrangements), but the notice and prohibited-practices framework reaches all residential tenancies.
-- [NH] - mobile_home / rv_spot: RSA 205-A (Regulation of Manufactured Housing Parks) governs manufactured/mobile home parks. RSA 205-A:9 makes RSA 540 applicable where not inconsistent. RV long-term lot rental is not separately codified; where an RV is used as a manufactured-home-park-style long-term residence it would fall under 205-A by analogy, but NH statute does not name RVs explicitly — rv_spot mapping to 205-A is the closest fit, not an express statutory grant.
-- [NH] - commercial: No dedicated commercial-tenancy act. Nonresidential/"nonrestricted property" tenancies are handled under RSA 540 (e.g., 540:3 gives 7 days' / 3 months' notice rules for nonresidential), with the rest left to contract.
-- [NH] - storage: RSA 451-C (Self-Service Storage Facility Liens) governs self-storage; it is NOT a residential statute.
-- [NH] PROVISIONS DELIBERATELY OMITTED (statute does not specify a residential value — no number invented):
-- [NH] - entry_notice_hours: OMITTED. RSA 540-A:3, IV prohibits a landlord from willfully entering the tenant's premises "without prior consent, other than to make emergency repairs," but sets NO general minimum number of advance-notice hours for routine entry. The only hour-figure in the chapter (48 hours' written notice) is narrowly limited to bed-bug inspection/treatment entry, not general entry, so there is no general entry_notice_hours value to record.
-- [NH] - late_fee_max_pct: OMITTED for residential. NH's residential statutes (RSA 540, 540-A) do NOT cap residential late fees and impose no percentage limit. IMPORTANT TRAP AVOIDED: RSA 451-C:7 contains a "$20 or 20 percent ... whichever is greater" late-fee standard, but RSA 451-C is the SELF-SERVICE STORAGE FACILITY LIENS chapter (Title XLI), applying only to storage-unit operators — it does NOT apply to residential rent. Do not attribute that cap to residential tenancies.
-- [NH] - late_fee_grace_days: OMITTED for residential. No residential grace period is set in RSA 540/540-A. The 5-day grace ("late fee shall not be imposed if the renter pays ... in full by the fifth day after the due date") is again RSA 451-C:7 — storage only — not residential.
-- [NH] NOTE on notice_to_vacate: RSA 540:3, II's flat 30-day residential notice has a 7-day exception for specified for-cause grounds (RSA 540:2, II(a),(b),(d),(h) — nonpayment, substantial damage, etc.). The recorded value (30 days, min) reflects the baseline no-fault month-to-month termination notice.
--
-- [ME] Sources are the official Maine Legislature statute site (legislature.maine.gov / mainelegislature.org), current through the First Special Session of the 132nd Legislature (Oct. 2025).
-- [ME] ACT SCOPE:
-- [ME] - RESIDENTIAL: General residential landlord-tenant law is split across two chapters of Title 14. Chapter 710 (Rental Property, §§6001-6030) covers tenancy-at-will termination, access/entry, late fees, habitability, evictions; Chapter 710-A (§§6031-6039) covers security deposits and is expressly limited to "residential rental units" / "a dwelling intended for human habitation." Treated here as a single residential act keyed to the §6032 "dwelling intended for human habitation" scope. Covers apartment and single_family.
-- [ME] - MOBILE_HOME_PARK: Title 10, Chapter 953 governs mobile home parks with its own parallel provisions (entry/detainer §9097-B, late-payment penalties §9097-C, security deposits §9098, habitability §9099). It is SEPARATE from the Title 14 residential act and tenants in mobile home parks are governed by Ch. 953, not Ch. 710.
-- [ME] RV / rv_spot: Maine has NO dedicated RV-park or recreational-vehicle long-term tenancy act. The Title 10 Ch. 953 definitions (§9091) define "mobile home" as a structure 8+ body feet wide, 32+ body feet long, built on a permanent chassis — which excludes recreational vehicles and travel trailers. RVs are therefore not covered by the mobile-home-park act and have no separate statute, so no act is mapped to rv_spot.
-- [ME] COMMERCIAL / storage: Maine has no dedicated commercial-tenancy statute; commercial leases are governed by general contract/common law and the eviction (forcible entry & detainer) procedures of Title 14 Ch. 709, not a substantive landlord-tenant code. Self-storage is governed by a separate lien statute (Title 10 Ch. 763, Self-Service Storage Facilities) which is not a landlord-tenant act in the residential sense. No act mapped to commercial or storage.
-- [ME] RESIDENTIAL PROVISIONS — all six requested provisions ARE specified in Maine statute and are included with verbatim evidence:
-- [ME] - deposit_return_days: §6033 sets two different deadlines — 21 days for a tenancy at will, and up to 30 days (as stated in the agreement) for a written lease. The 30-day figure (the statutory maximum for written agreements) is recorded as the ruleKind=max value; note the 21-day tenancy-at-will deadline in implementation.
-- [ME] - entry_notice_hours: §6025 does not impose an absolute hard requirement — it requires "reasonable notice" and creates a rebuttable presumption that 24 hours is reasonable. Recorded as 24 (min) on that presumption.
-- [ME] - late_fee: §6028 caps the penalty at 4% of one month's rent and provides a 15-day grace period (rent is "late" only after 15 days). Section also requires the landlord to give written notice of the penalty at lease signing.
--
-- [RI] Sources are the official RI General Assembly statute server (webserver.rilegislature.gov). RESIDENTIAL = ch. 34-18 (URLTA-based), governing standard dwelling units (apartments, single-family).
-- [RI] OMITTED provisions (statute specifies no value — did not invent):
-- [RI] - late_fee_max_pct: Ch. 34-18 imposes no cap on late fees. No section caps or sets a percentage; late fees are unregulated as to amount.
-- [RI] - late_fee_grace_days: Ch. 34-18 has no grace period before a late fee may be charged. The 15-day figure in § 34-18-35 ("If any part of the stipulated rent is due and in arrears for fifteen (15) days, the landlord shall send a written notice") is the threshold for an EVICTION-FOR-NONPAYMENT demand notice, NOT a late-fee grace period — so it is not encoded as late_fee_grace_days.
-- [RI] UNIT-TYPE COVERAGE notes:
-- [RI] - rv_spot: No dedicated long-term RV-tenancy act in RI. RV parks/campgrounds are regulated under Title 32, ch. 32-7 (health/safety/licensing of RV parks and campgrounds), which is NOT a landlord-tenant tenancy statute. Long-term RV occupants may be tenants under general law, but no statute squarely assigns RV-spot tenancies to 34-18 or 31-44, so rv_spot is not asserted under any act here.
-- [RI] - storage: No self-storage / self-service-storage-facility lien act surfaced within the landlord-tenant titles searched; not represented.
-- [RI] - mobile_home: ch. 31-44 (Title 31) governs mobile/manufactured home park tenancies (separate from 34-18) — includes §§ 31-44-2 evictions/termination, 31-44-7 lease, 31-44-7.1 security deposits.
-- [RI] ENTRY notice: statute states "two (2) days" — converted to 48 hours for the hours-based schema field.
--
-- [MT] Official source: Montana Code Annotated on the Montana Legislature site. Note the legacy host leg.mt.gov 301-redirects to archive.legmt.gov and then to the canonical mca.legmt.gov; all URLs above use the canonical host.
-- [MT] ACTS:
-- [MT] - Residential (Ch. 24): governs dwelling units — apartments and single-family. Long-term RV occupancy for residential dwelling purposes (30+ consecutive days) falls under residential/mobile-home framework rather than a separate act; short-term/transient RV-park and campground stays (<30 days) are EXCLUDED from Ch. 24 per 70-24-104 / SB251 (2017). Mapped rv_spot to both Ch. 24 and Ch. 33 to reflect this; there is no standalone RV act.
-- [MT] - Mobile Home (Ch. 33): Montana Residential Mobile Home Lot Rental Act — lot/space rental to owners of mobile/manufactured homes; also covers long-term RV space rentals used as residential dwellings. 90-day termination notice for legitimate business reasons; 6-month notice on change of park use.
-- [MT] - Storage (Ch. 6 Part 6): Self-Storage Facilities Act — operator's lien, 60-day default before lien sale.
-- [MT] - Commercial (Ch. 26): Montana has NO comprehensive dedicated commercial-tenancy act. Ch. 26 ("Landlord and Tenant — Residential and Commercial") is a thin set of general lease provisions (assignment, attornment, change of lease terms by notice at 70-26-109, etc.) applying to both residential and commercial; commercial tenancies are otherwise governed by the parties' contract and common law.
-- [MT] RESIDENTIAL PROVISIONS — included:
-- [MT] - entry_notice_hours = 24 (70-24-312).
-- [MT] - deposit_return_days = 30 (70-25-202). Security deposits are governed by a SEPARATE chapter (Ch. 25, Residential Tenants' Security Deposits), cross-referenced by Ch. 24 at 70-24-112. The 30-day outer deadline applies when there are any deductions (the landlord must furnish a written list of damages/charges and refund the balance within 30 days); a shorter 10-day deadline applies ONLY when there are zero damages, no cleaning, no unpaid rent, and no unpaid utilities ('the landlord shall return the security deposit within 10 days', 70-25-202). Recorded 30 as the general statutory max.
-- [MT] - notice_to_vacate_days = 30 (70-24-441).
-- [MT] RESIDENTIAL PROVISIONS — OMITTED (no statutory value exists; not invented):
-- [MT] - deposit_max_months: Montana does NOT cap security deposit amount. Reviewed entire Ch. 25 (70-25-101 through 70-25-206) — no cap-by-months or dollar-cap section exists.
-- [MT] - late_fee_max_pct: Montana does NOT cap late fees. 70-24-201 leaves rent/late-fee terms to the rental agreement ('Rent means all payments... including rent, late fees, or other charges as agreed on in the rental agreement'); no statutory percentage cap.
-- [MT] - late_fee_grace_days: No statutory grace period before a late fee may apply; rent is 'payable without demand or notice at the time and place agreed upon' (70-24-201). Omitted.
--
-- [DE] All provisions verified against the official Delaware Code at delcode.delaware.gov (Title 25). The residential act is a multi-chapter body (the "Residential Landlord-Tenant Code," 25 Del. C. ch. 51-59); § 5101 applies it to residential rental units statewide, and § 5101(b) expressly excludes commercial rental units (which fall to ch. 61 / general contract principles). § 5102 also excludes hotels/motels/transient lodging and short-term coastal rentals of 120 days or less.
-- [DE] rv_spot mapping: Delaware has NO separate RV-park statute. Chapter 70 is limited to "manufactured homes" (HUD-code/mobile homes) and manufactured-home community lots; an RV is not a manufactured home under the Act, so a long-term RV lot rental defaults to the Residential Landlord-Tenant Code (ch. 51-59). I mapped rv_spot under the residential act for that reason; if GAM wants RV spots treated as park-model/manufactured-home lots in a given community, ch. 70 could apply instead.
-- [DE] Chapter 70 (manufactured homes) has its own deposit, rent-increase (CPI-U capped, once per 12 months), and termination rules that differ from the residential figures above; in the absence of a ch. 70 provision, the Residential Landlord-Tenant Code governs (25 Del. C. § 7003).
-- [DE] Deposit note: the 1-month cap (§ 5514(a)(2)) applies to leases of 1 year or more; for month-to-month tenancies the statute does not impose the same 1-month ceiling, and pet deposits up to 1 month and furnished-unit surcharges are separately allowed under § 5514. The 20-day return clock and double-damages penalty for wrongful withholding apply across the board.
-- [DE] Late fee note: § 5501(d) also extends the rent due date by 3 days if the landlord fails to maintain a payment office in the county where the unit is located — relevant to when the 5-day grace begins.
--
-- [SD] South Dakota does NOT have separate mobile-home-park or RV-park acts. All real-property leases fall under SDCL ch. 43-32 (Lease of Real Property): single-family/apartments are the core residential coverage; mobile/manufactured homes are addressed within it (43-32-31 governs 90-day notice to vacate/remove a mobile or manufactured home); RV park long-term stays are addressed by 43-32-37 (ejection from hotel/campground/RV park premises); commercial leases are covered too (43-32-24.1 commercial security deposits). Self-storage is the only separate regime, under SDCL ch. 44-14 (Self-Service Storage Facilities Liens), which is a lien statute, not a tenancy act.
-- [SD] OMITTED provisions (no statute exists — not invented): (1) late_fee_max_pct — South Dakota imposes no statutory cap on late fees; ch. 43-32 (sections 43-32-1 through 43-32-37) contains no late-fee section. (2) late_fee_grace_days — no mandatory grace period exists in statute; rent is late on the date the lease specifies unless the lease grants a grace period.
-- [SD] deposit_return_days CAUTION / version transition: SDCL 43-32-24 has two versions. The version EFFECTIVE THROUGH June 30, 2026 requires return 'within two weeks' (14 days): 'Every lessor of residential premises shall, within two weeks after the termination of the tenancy and receipt of the tenant's mailing address or delivery instructions, return the security deposit ...'. The amended version EFFECTIVE JULY 1, 2026 changes this to twenty-one days. I seeded 21 days because it is the durable forward-looking value as of the database build, but if the reference DB must reflect law in force exactly on today's date (2026-06-11), the in-force value is 14 days until 2026-06-30. Both versions also require, on request, an itemized accounting within 45 days, forfeiture of withholding rights for noncompliance, and punitive damages up to $200 for bad-faith retention.
-- [SD] notice_to_vacate_days basis: 43-32-15 caps the required termination notice at 'not exceeding one month'; for a month-to-month tenancy the term is one month, yielding ~30 days. 43-32-13 separately uses thirty-day language for landlord modification of month-to-month terms (and gives the tenant 15 days after a modification notice to terminate effective the first of the next month). The 30-day month-to-month termination figure is well-supported but is derived from the 'one month' statutory term rather than an explicit numeric '30 days' in the general-termination section.
--
-- [ND] All residential values verified verbatim from the official North Dakota Legislative Branch PDF (ndlegis.gov) for NDCC ch. 47-16; the chapter PDF was downloaded and text-extracted to confirm exact wording.
-- [ND] OMITTED provisions (statute does NOT specify a value — not invented):
-- [ND] - entry_notice_hours: NDCC § 47-16-07.3 ("When landlord may enter apartment") sets NO fixed advance-notice hours/days. It permits entry "only during reasonable hours, and in a reasonable manner" and requires that "[u]nless it is impractical to do so the landlord shall first notify and receive the consent of the tenant... which consent shall identify a time certain." No numeric notice period exists, so omitted.
-- [ND] - late_fee_max_pct and late_fee_grace_days: Chapter 47-16 contains NO late-fee provision whatsoever (grep of the full official chapter text returned zero matches for late fee/charge/grace). North Dakota does not cap residential late fees or mandate a grace period by statute. Both omitted.
-- [ND] - deposit_max_months note: base cap is 1 month's rent. § 47-16-07.1(1)(a)-(b) allows up to 2 months only for tenants convicted of a felony or with a prior judgment for violating a rental agreement; a separate pet deposit (not a general security deposit) may be the greater of $2,500 or 2 months' rent under § 47-16-07.1(2). The min/max model captures the general residential ceiling of 1 month.
-- [ND] ACTS / coverage notes:
-- [ND] - North Dakota has NO standalone Uniform Residential Landlord & Tenant Act and NO dedicated mobile-home-park or RV-park tenancy act. The general 'Leasing of Real Property' chapter (NDCC ch. 47-16) governs apartments, single-family dwellings, and — by default — mobile-home lot rentals and RV long-term tenancies. It is a general real-property leasing chapter (also contains farm-lease and oil/gas-lease sections), so commercial leases also fall under it absent a separate commercial statute.
-- [ND] - Mobile home parks get ONE supplemental statute: NDCC § 47-10-28 (located in ch. 47-10 'Real Property Transfers'), which adds mobile-home-park-specific tenant protections — notably a 90-day notice requirement before any rent increase on month-to-month mobile-home-park tenancies ('Any month-to-month tenancy agreement must provide a minimum of ninety days' notice to the tenant before any rent increase is effective'), ownership-transfer disclosure within 5 business days, and a 6-month rent-freeze on new owners in certain cases. This is NOT a full tenancy code; mobile-home park tenancies still rely on ch. 47-16 for deposits, return, entry, and termination. Verified verbatim from ndlegis.gov ch. 47-10 PDF.
-- [ND] - Storage: self-service storage rentals are governed by the lien framework in NDCC ch. 35-33 (Title 35 Liens), not by 47-16. (ND also has ch. 35-36 'Portable Storage Unit Property Lien' for portable units.) These are lien/enforcement statutes, not landlord-tenant deposit/entry statutes, so no 47-16-style provisions apply.
-- [ND] - rv_spot was mapped to the residential act (ch. 47-16) because ND has no RV-park-specific tenancy statute; long-term RV lot rentals default to the general leasing chapter.
--
-- [AK] Source: Alaska State Legislature official statutes (akleg.gov), Alaska Statutes 2024. Verified verbatim from the statute print interface.
-- [AK] ACT COVERAGE: Alaska has ONE residential act, the Uniform Residential Landlord and Tenant Act (AS 34.03, short title confirmed at AS 34.03.380). It governs all residential dwelling units. "Dwelling unit" is defined broadly at AS 34.03.360(3) as "a structure or a part of a structure that is used as a home, residence, or sleeping place," which covers apartments, single-family houses, mobile homes, and RVs used as long-term residences. Transient occupancy in a hotel/motel/lodging is excluded (AS 34.03.330(b)(4)).
-- [AK] MOBILE HOME / RV: There is NO separate mobile-home-park or RV-park act in Alaska. Mobile home park tenancies are governed by URLTA itself, with ADDITIONAL eviction/notice protections embedded at AS 34.03.225 (e.g., a mobile home park operator may evict only for enumerated reasons; a change in land use requires at least 270 days' notice). RV long-term tenants used as a residence fall under URLTA via the general "dwelling unit" definition; rv_spot is mapped to the residential act accordingly.
-- [AK] COMMERCIAL: Alaska has no dedicated commercial landlord-tenant statute. URLTA applies only to residential dwelling units; commercial leases are governed by the lease contract and common law. No commercial act returned in the structured acts list.
-- [AK] STORAGE: Self-storage is covered by the Self-Storage Facility Liens statute (AS 34.35.600 - 34.35.695), a lien-enforcement statute rather than a full tenancy act. Note: this storage statute contains a late-fee provision (reasonable if not exceeding the greater of $20 or 20% of monthly rent) but that applies ONLY to self-storage, NOT to residential tenancies.
-- [AK] OMITTED RESIDENTIAL PROVISIONS (statute does NOT specify - not invented):
-- [AK] - late_fee_max_pct: OMITTED. URLTA imposes no cap on residential late fees. AS 34.03.020 leaves rent and fee terms to the parties' agreement ("The landlord and tenant may include in a rental agreement clauses and conditions not prohibited by this chapter or by law, including rent, terms of agreement"). No statutory percentage cap exists in AS 34.03.
-- [AK] - late_fee_grace_days: OMITTED. No statutory grace period before a residential late fee may apply. Rent is "payable without demand or notice at the time and place agreed upon" (AS 34.03.020(c)); no grace period is mandated by the act.
-- [AK] DEPOSIT RETURN NUANCE: AS 34.03.070(g) sets 14 days as the default return deadline; this extends to 30 days if the landlord deducts for damages under AS 34.03.120. The minimum/default statutory deadline (14 days) is reported as deposit_return_days.
--
-- [VT] Source: official Vermont Legislature statutes site (legislature.vermont.gov). All values verified against actual statutory text.
-- [VT] ACTS:
-- [VT] - Residential act = 9 V.S.A. Chapter 137 "Residential Rental Agreements." Governs apartments and standard residential dwellings (single_family). § 4451 ties obligations to "residential rental agreements" / "dwelling units."
-- [VT] - Mobile home parks = 10 V.S.A. Chapter 153, a SEPARATE statute governing lot rentals in mobile home parks (mobile_home unit type).
-- [VT] - RV / rv_spot: NO separate Vermont act, and explicitly EXCLUDED from the mobile-home-park chapter by 10 V.S.A. § 6204: "This chapter shall not apply to the rental or use of campsites occupied for vacation or recreational purposes by camping units, such as: tents, yurts, tepees, lean-tos, camping cabins, and recreational vehicles, including motor homes, folding camping trailers, conventional travel trailers, fifth wheel travel trailers, truck campers, van campers, and conversion vehicles..." Long-term RV/campsite occupancy in VT is not covered by either the residential or mobile-home statutes (common-law / contract). rv_spot intentionally NOT mapped to any act.
-- [VT] - commercial and storage: NO Vermont statutory landlord-tenant act. Chapter 137 is residential-only; commercial leases and self-storage are governed by common law / contract (and any separate lien statutes), not a tenancy act. No act returned for these unit types.
-- [VT] PROVISIONS (residential, Chapter 137):
-- [VT] - entry_notice_hours = 48h min (§ 4460(b)), entry permitted 9:00 A.M.–9:00 P.M.
-- [VT] - deposit_return_days = 14 days standard (§ 4461(a)). Note: a separate 60-day window applies to seasonal/non-primary-residence rentals; the 14-day general rule is recorded as the residential default.
-- [VT] - notice_to_vacate_days = 60 days min (§ 4467(c)(1)(A)) for tenancies of two years or less; rises to 90 days for tenancies over two years (§ 4467(c)(1)(B)). Recorded the 60-day floor.
-- [VT] OMITTED (statute does not specify — not invented):
-- [VT] - deposit_max_months: Vermont Chapter 137 has NO cap on security deposit amount. OMITTED.
-- [VT] - late_fee_max_pct and late_fee_grace_days: Chapter 137 contains NO late-fee provisions — no max percentage, no dollar cap, no grace period. Confirmed absent in full-chapter review. Both OMITTED.
--
-- [WY] SOURCE: All statutory text verified directly from the official Wyoming Legislature site (wyoleg.gov), Title 1, Chapter 21, Article 12 (Residential Rental Property Act).
-- [WY] ACT SCOPE: Wyoming has only ONE substantive landlord-tenant act — the Residential Rental Property Act (Wyo. Stat. §§ 1-21-1201 to 1-21-1211). It is a minimal-regulation statute. Per the § 1-21-1201 definition of "residential rental unit," it covers a renter's principal place of residence (apartments, single-family dwellings) but EXPRESSLY EXCLUDES "a mobile home lot or recreational property rented on an occasional basis." Exact language: '"Residential rental unit" means a renter's principal place of residence and includes the appurtenances, grounds, common areas and facilities... excluding a mobile home lot or recreational property rented on an occasional basis.'
-- [WY] NO SEPARATE MOBILE HOME PARK ACT or RV PARK ACT exists in Wyoming. Mobile home lots, RV spaces, commercial, and storage rentals fall to general contract/common law for substantive terms; the only statutory framework touching them is the Forcible Entry and Detainer eviction procedure (Title 1, Ch. 21, Art. 10, §§ 1-21-1001 et seq.), which is procedural (notice to quit / eviction), not a substantive landlord-tenant rights act. Title 31, Ch. 2, Art. 5 covers mobile-home TITLING only, not park tenancy rights. The "eviction_fed" act entry is included to map those unit types to the only applicable Wyoming statute; it is procedural and was NOT mined for the residential provisions below.
-- [WY] PROVISIONS DELIBERATELY OMITTED (no statutory value exists — not invented):
-- [WY] - entry_notice_hours: NO STATUTE. The Residential Rental Property Act contains no landlord-entry notice provision. Practice requires only "reasonable" notice; no hours are fixed by statute.
-- [WY] - deposit_max_months: NO STATUTE. Wyoming sets no maximum security deposit. § 1-21-1207 only requires written notice of any NON-refundable portion; it does not cap the amount.
-- [WY] - late_fee_max_pct: NO STATUTE. The act is silent on late fees; no percentage cap.
-- [WY] - late_fee_grace_days: NO STATUTE. No mandatory grace period.
-- [WY] - notice_to_vacate_days: NO STATUTE. Wyoming has no statute setting a month-to-month termination notice period. The commonly-cited "30 days" is a common-law/customary default that the lease may modify; it is expressly NOT statutory. (§ 1-21-1003's 3-day notice to quit is an eviction-for-cause procedure, not a no-cause month-to-month termination period, so it does not map to notice_to_vacate_days.) Omitted per the no-invention rule.
-- [WY] The ONLY quantified provision in the residential act is the 30-day deposit-return deadline (§ 1-21-1208), with a statutory 30-day extension where there is damage to the unit ("If there is damage to the residential rental unit, this period shall be extended by thirty (30) days.").
--

INSERT INTO public.state_landlord_tenant_acts
  (state_code, act_key, act_name, unit_types, official_url, summary, source_date, effective_year)
VALUES
  ('NH', 'residential', 'Actions Against Tenants (RSA 540) and Prohibited Practices and Security Deposits (RSA 540-A)', ARRAY['apartment','single_family']::text[], 'https://gc.nh.gov/rsa/html/NHTOC/NHTOC-LV-540-A.htm', 'RSA ch. 540 and RSA ch. 540-A', DATE '2026-06-11', 2026),
  ('NH', 'mobile_home_park', 'Regulation of Manufactured Housing Parks', ARRAY['mobile_home','rv_spot']::text[], 'https://gc.nh.gov/rsa/html/NHTOC/NHTOC-XVII-205-A.htm', 'RSA ch. 205-A', DATE '2026-06-11', 2026),
  ('NH', 'commercial', 'Actions Against Tenants (nonrestricted/nonresidential property provisions)', ARRAY['commercial']::text[], 'https://gc.nh.gov/rsa/html/lv/540/540-mrg.htm', 'RSA ch. 540', DATE '2026-06-11', 2026),
  ('NH', 'self_service_storage', 'Self-Service Storage Facility Liens', ARRAY['storage']::text[], 'https://gc.nh.gov/rsa/html/NHTOC/NHTOC-XLI-451-C.htm', 'RSA ch. 451-C', DATE '2026-06-11', 2026),
  ('ME', 'residential', 'Title 14, Chapter 710 — Rental Property (with Chapter 710-A — Security Deposits on Residential Rental Units)', ARRAY['apartment','single_family']::text[], 'https://legislature.maine.gov/statutes/14/title14ch710sec0.html', 'Me. Rev. Stat. tit. 14, ch. 710 & 710-A (§§ 6001-6045)', DATE '2026-06-11', 2026),
  ('ME', 'mobile_home_park', 'Title 10, Chapter 953 — Regulation of Mobile Home Parks; Landlord and Tenant', ARRAY['mobile_home']::text[], 'https://www.mainelegislature.org/legis/statutes/10/title10ch953sec0.html', 'Me. Rev. Stat. tit. 10, ch. 953 (§§ 9091-9100)', DATE '2026-06-11', 2026),
  ('RI', 'residential', 'Residential Landlord and Tenant Act', ARRAY['apartment','single_family']::text[], 'https://webserver.rilegislature.gov/Statutes/TITLE34/34-18/INDEX.htm', 'R.I. Gen. Laws ch. 34-18', DATE '2026-06-11', 2026),
  ('RI', 'mobile_home_park', 'Mobile and Manufactured Homes', ARRAY['mobile_home']::text[], 'https://webserver.rilegislature.gov/Statutes/TITLE31/31-44/INDEX.htm', 'R.I. Gen. Laws ch. 31-44', DATE '2026-06-11', 2026),
  ('RI', 'commercial', 'Commercial Leasing and Other Estates', ARRAY['commercial']::text[], 'https://webserver.rilegislature.gov/Statutes/TITLE34/34-18.1/INDEX.htm', 'R.I. Gen. Laws ch. 34-18.1', DATE '2026-06-11', 2026),
  ('MT', 'residential', 'Residential Landlord and Tenant Act of 1977', ARRAY['apartment','single_family','rv_spot']::text[], 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0240/parts_index.html', 'Mont. Code Ann. Title 70, Chapter 24 (70-24-101 et seq.)', DATE '2026-06-11', 2026),
  ('MT', 'mobile_home_park', 'Montana Residential Mobile Home Lot Rental Act', ARRAY['mobile_home','rv_spot']::text[], 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0330/parts_index.html', 'Mont. Code Ann. Title 70, Chapter 33 (70-33-101 et seq.)', DATE '2026-06-11', 2026),
  ('MT', 'storage', 'Self-Storage Facilities Act', ARRAY['storage']::text[], 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0060/part_0060/sections_index.html', 'Mont. Code Ann. Title 70, Chapter 6, Part 6 (70-6-601 et seq.)', DATE '2026-06-11', 2026),
  ('MT', 'commercial', 'Landlord and Tenant — Residential and Commercial (general provisions)', ARRAY['commercial']::text[], 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0260/part_0010/sections_index.html', 'Mont. Code Ann. Title 70, Chapter 26 (70-26-101 et seq.)', DATE '2026-06-11', 2026),
  ('DE', 'residential', 'Residential Landlord-Tenant Code', ARRAY['apartment','single_family','rv_spot']::text[], 'https://delcode.delaware.gov/title25/c051/', '25 Del. C. ch. 51-59 (esp. ch. 51 General Provisions, ch. 53 Landlord Obligations & Tenant Remedies, ch. 55 Tenant Obligations & Landlord Remedies)', DATE '2026-06-11', 2026),
  ('DE', 'mobile_home_park', 'Manufactured Homes and Manufactured Home Communities Act', ARRAY['mobile_home']::text[], 'https://delcode.delaware.gov/title25/c070/', '25 Del. C. ch. 70', DATE '2026-06-11', 2026),
  ('DE', 'commercial', 'Commercial Leases', ARRAY['commercial']::text[], 'https://delcode.delaware.gov/title25/c061/', '25 Del. C. ch. 61', DATE '2026-06-11', 2026),
  ('DE', 'self_service_storage', 'Self-Service Storage Facilities Act', ARRAY['storage']::text[], 'https://delcode.delaware.gov/title25/c049/', '25 Del. C. ch. 49', DATE '2026-06-11', 2026),
  ('SD', 'residential', 'Lease of Real Property', ARRAY['apartment','single_family','mobile_home','rv_spot','commercial']::text[], 'https://sdlegislature.gov/Statutes/43-32', 'SDCL ch. 43-32', DATE '2026-06-11', 2026),
  ('SD', 'storage', 'Self-Service Storage Facilities Liens', ARRAY['storage']::text[], 'https://sdlegislature.gov/Statutes/44-14', 'SDCL ch. 44-14', DATE '2026-06-11', 2026),
  ('ND', 'residential', 'Leasing of Real Property (general landlord-tenant law)', ARRAY['apartment','single_family','mobile_home','rv_spot','commercial']::text[], 'https://ndlegis.gov/cencode/t47c16.pdf', 'N.D. Cent. Code ch. 47-16', DATE '2026-06-11', 2026),
  ('ND', 'mobile_home_park', 'Mobile Home Park - Ownership, Transfer, Tenant Rights (within Real Property Transfers)', ARRAY['mobile_home']::text[], 'https://ndlegis.gov/cencode/t47c10.pdf', 'N.D. Cent. Code § 47-10-28', DATE '2026-06-11', 2026),
  ('ND', 'storage', 'Self-Service Storage Facility Liens', ARRAY['storage']::text[], 'https://ndlegis.gov/cencode/t35c33.pdf', 'N.D. Cent. Code ch. 35-33', DATE '2026-06-11', 2026),
  ('AK', 'residential', 'Uniform Residential Landlord and Tenant Act (URLTA)', ARRAY['apartment','single_family','mobile_home','rv_spot']::text[], 'https://www.akleg.gov/basis/statutes.asp#34.03', 'AS 34.03 (AS 34.03.010 - 34.03.380)', DATE '2026-06-11', 2026),
  ('AK', 'self_storage', 'Self-Storage Facility Liens', ARRAY['storage']::text[], 'https://www.akleg.gov/basis/statutes.asp#34.35.600', 'AS 34.35.600 - 34.35.695', DATE '2026-06-11', 2026),
  ('VT', 'residential', 'Residential Rental Agreements', ARRAY['apartment','single_family']::text[], 'https://legislature.vermont.gov/statutes/chapter/09/137', '9 V.S.A. Chapter 137 (§§ 4451–4469a)', DATE '2026-06-11', 2026),
  ('VT', 'mobile_home_park', 'Mobile Home Parks', ARRAY['mobile_home']::text[], 'https://legislature.vermont.gov/statutes/chapter/10/153', '10 V.S.A. Chapter 153 (§§ 6201–6266)', DATE '2026-06-11', 2026),
  ('WY', 'residential', 'Residential Rental Property Act', ARRAY['apartment','single_family']::text[], 'https://wyoleg.gov/NXT/gateway.dll/Statutes/2021%20Titles/2/54/66', 'Wyo. Stat. §§ 1-21-1201 to 1-21-1211 (Title 1, Chapter 21, Article 12)', DATE '2026-06-11', 2026),
  ('WY', 'eviction_fed', 'Forcible Entry and Detainer (eviction procedure — applies across tenancy types; no separate substantive landlord-tenant act for mobile home parks, RV spaces, commercial, or storage)', ARRAY['mobile_home','rv_spot','commercial','storage']::text[], 'https://wyoleg.gov/NXT/gateway.dll/Statutes/2021%20Titles/2/54/64', 'Wyo. Stat. §§ 1-21-1001 to 1-21-1016 (Title 1, Chapter 21, Article 10)', DATE '2026-06-11', 2026);

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'NH', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('deposit_max_months', 'max', 1::numeric, 'months of rent', 'A security deposit may not exceed 1 month of rent.', 'RSA 540-A:6, I(a)', 'https://gc.nh.gov/rsa/html/lv/540-A/540-A-6.htm'),
  ('deposit_return_days', 'max', 30::numeric, 'days', 'The deposit must be returned within 30 days after the tenancy ends.', 'RSA 540-A:7', 'https://gc.nh.gov/rsa/html/lv/540-A/540-A-7.htm'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'RSA 540:3, II', 'https://gc.nh.gov/rsa/html/lv/540/540-3.htm')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'NH' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'ME', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 24::numeric, 'hours', 'At least 24 hours'' advance notice is generally required before the landlord enters.', 'Me. Rev. Stat. tit. 14, § 6025(2)', 'https://legislature.maine.gov/statutes/14/title14sec6025.html'),
  ('deposit_max_months', 'max', 2::numeric, 'months of rent', 'A security deposit may not exceed 2 months of rent.', 'Me. Rev. Stat. tit. 14, § 6032', 'https://legislature.maine.gov/statutes/14/title14sec6032.html'),
  ('deposit_return_days', 'max', 30::numeric, 'days', 'The deposit must be returned within 30 days after the tenancy ends.', 'Me. Rev. Stat. tit. 14, § 6033(2)', 'https://legislature.maine.gov/statutes/14/title14sec6033.html'),
  ('late_fee_max_pct', 'max', 4::numeric, '% of rent', 'A late fee may not exceed 4% of the rent.', 'Me. Rev. Stat. tit. 14, § 6028(1)', 'https://legislature.maine.gov/statutes/14/title14sec6028.html'),
  ('late_fee_grace_days', 'min', 15::numeric, 'days', 'A late fee may not be charged until at least 15 days after rent is due.', 'Me. Rev. Stat. tit. 14, § 6028(1)', 'https://legislature.maine.gov/statutes/14/title14sec6028.html'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'Me. Rev. Stat. tit. 14, § 6002(1)', 'https://legislature.maine.gov/statutes/14/title14sec6002.html')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'ME' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'RI', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 48::numeric, 'hours', 'At least 48 hours'' advance notice is generally required before the landlord enters.', 'R.I. Gen. Laws § 34-18-26(c)', 'https://webserver.rilegislature.gov/Statutes/TITLE34/34-18/34-18-26.htm'),
  ('deposit_max_months', 'max', 1::numeric, 'months of rent', 'A security deposit may not exceed 1 month of rent.', 'R.I. Gen. Laws § 34-18-19', 'https://webserver.rilegislature.gov/Statutes/TITLE34/34-18/34-18-19.htm'),
  ('deposit_return_days', 'max', 20::numeric, 'days', 'The deposit must be returned within 20 days after the tenancy ends.', 'R.I. Gen. Laws § 34-18-19', 'https://webserver.rilegislature.gov/Statutes/TITLE34/34-18/34-18-19.htm'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'R.I. Gen. Laws § 34-18-37(b)', 'https://webserver.rilegislature.gov/Statutes/TITLE34/34-18/34-18-37.htm')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'RI' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'MT', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 24::numeric, 'hours', 'At least 24 hours'' advance notice is generally required before the landlord enters.', 'Mont. Code Ann. 70-24-312(2)', 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0240/part_0030/section_0120/0700-0240-0030-0120.html'),
  ('deposit_return_days', 'max', 30::numeric, 'days', 'The deposit must be returned within 30 days after the tenancy ends.', 'Mont. Code Ann. 70-25-202', 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0250/part_0020/section_0020/0700-0250-0020-0020.html'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'Mont. Code Ann. 70-24-441(1)', 'https://mca.legmt.gov/bills/mca/title_0700/chapter_0240/part_0040/section_0410/0700-0240-0040-0410.html')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'MT' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'DE', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 48::numeric, 'hours', 'At least 48 hours'' advance notice is generally required before the landlord enters.', '25 Del. C. § 5509(b)', 'https://delcode.delaware.gov/title25/c055/'),
  ('deposit_max_months', 'max', 1::numeric, 'months of rent', 'A security deposit may not exceed 1 month of rent.', '25 Del. C. § 5514(a)(2)', 'https://delcode.delaware.gov/title25/c055/'),
  ('deposit_return_days', 'max', 20::numeric, 'days', 'The deposit must be returned within 20 days after the tenancy ends.', '25 Del. C. § 5514(f)', 'https://delcode.delaware.gov/title25/c055/'),
  ('late_fee_max_pct', 'max', 5::numeric, '% of rent', 'A late fee may not exceed 5% of the rent.', '25 Del. C. § 5501(d)', 'https://delcode.delaware.gov/title25/c055/'),
  ('late_fee_grace_days', 'min', 5::numeric, 'days', 'A late fee may not be charged until at least 5 days after rent is due.', '25 Del. C. § 5501(d)', 'https://delcode.delaware.gov/title25/c055/'),
  ('notice_to_vacate_days', 'min', 60::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 60 days'' notice.', '25 Del. C. § 5106(d)', 'https://delcode.delaware.gov/title25/c051/sc01/')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'DE' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'SD', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 24::numeric, 'hours', 'At least 24 hours'' advance notice is generally required before the landlord enters.', 'SDCL 43-32-32', 'https://sdlegislature.gov/Statutes/43-32-32'),
  ('deposit_max_months', 'max', 1::numeric, 'months of rent', 'A security deposit may not exceed 1 month of rent.', 'SDCL 43-32-6.1', 'https://sdlegislature.gov/Statutes/43-32-6.1'),
  ('deposit_return_days', 'max', 14::numeric, 'days', 'The deposit must be returned within 14 days after the tenancy ends.', 'SDCL 43-32-24', 'https://sdlegislature.gov/Statutes/43-32-24'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'SDCL 43-32-15', 'https://sdlegislature.gov/Statutes/43-32-15')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'SD' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'ND', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('deposit_max_months', 'max', 1::numeric, 'months of rent', 'A security deposit may not exceed 1 month of rent.', 'N.D. Cent. Code § 47-16-07.1(1)', 'https://ndlegis.gov/cencode/t47c16.pdf'),
  ('deposit_return_days', 'max', 30::numeric, 'days', 'The deposit must be returned within 30 days after the tenancy ends.', 'N.D. Cent. Code § 47-16-07.1(3)', 'https://ndlegis.gov/cencode/t47c16.pdf'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'N.D. Cent. Code § 47-16-15(2)', 'https://ndlegis.gov/cencode/t47c16.pdf')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'ND' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'AK', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 24::numeric, 'hours', 'At least 24 hours'' advance notice is generally required before the landlord enters.', 'AS 34.03.140(c)', 'https://www.akleg.gov/basis/statutes.asp#34.03.140'),
  ('deposit_max_months', 'max', 2::numeric, 'months of rent', 'A security deposit may not exceed 2 months of rent.', 'AS 34.03.070(a)', 'https://www.akleg.gov/basis/statutes.asp#34.03.070'),
  ('deposit_return_days', 'max', 14::numeric, 'days', 'The deposit must be returned within 14 days after the tenancy ends.', 'AS 34.03.070(g)', 'https://www.akleg.gov/basis/statutes.asp#34.03.070'),
  ('notice_to_vacate_days', 'min', 30::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 30 days'' notice.', 'AS 34.03.290(b)', 'https://www.akleg.gov/basis/statutes.asp#34.03.290')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'AK' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'VT', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('entry_notice_hours', 'min', 48::numeric, 'hours', 'At least 48 hours'' advance notice is generally required before the landlord enters.', '9 V.S.A. § 4460(b)', 'https://legislature.vermont.gov/statutes/section/09/137/04460'),
  ('deposit_return_days', 'max', 14::numeric, 'days', 'The deposit must be returned within 14 days after the tenancy ends.', '9 V.S.A. § 4461(c)', 'https://legislature.vermont.gov/statutes/section/09/137/04461'),
  ('notice_to_vacate_days', 'min', 60::numeric, 'days', 'Ending a month-to-month tenancy generally requires at least 60 days'' notice.', '9 V.S.A. § 4467(c)(1)(A)', 'https://legislature.vermont.gov/statutes/section/09/137/04467')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'VT' AND a.act_key = 'residential' AND a.effective_year = 2026;

INSERT INTO public.state_law_provisions
  (act_id, state_code, topic, rule_kind, threshold_numeric, threshold_unit, summary, statute_citation, source_url, source_date, effective_year)
SELECT a.id, 'WY', v.topic, v.rule_kind, v.threshold_numeric, v.threshold_unit, v.summary, v.citation, v.url, DATE '2026-06-11', 2026
FROM public.state_landlord_tenant_acts a CROSS JOIN (VALUES
  ('deposit_return_days', 'max', 30::numeric, 'days', 'The deposit must be returned within 30 days after the tenancy ends.', 'Wyo. Stat. § 1-21-1208(a)', 'https://wyoleg.gov/NXT/gateway.dll/Statutes/2021%20Titles/2/54/66')
) AS v(topic, rule_kind, threshold_numeric, threshold_unit, summary, citation, url)
WHERE a.state_code = 'WY' AND a.act_key = 'residential' AND a.effective_year = 2026;
