-- S605 (Nic): carry a tenant's outstanding balance onto the platform.
--
-- A landlord migrating from another system has tenants who already owe money.
-- There was no way to record it: every charge in GAM is generated by the billing
-- engine from a lease, so pre-platform arrears simply could not be entered. The
-- landlord's only options were to lose the debt or track it off-platform, which
-- defeats the reconciliation the bank feed exists to provide.
--
-- Modelled as a real invoice so it is payable, visible, and settles through the
-- ordinary payment path — a tenant should not have to be told their old balance
-- works differently from their rent.
--
-- LATE FEES ARE OFF BY DEFAULT, and that is the load-bearing decision here.
-- Nic: a tenant on a catch-up plan should not be fined for arrears carried over
-- from the old system. The late-fee engine walks unpaid invoices nightly, so
-- without an explicit exemption a $2,000 carried balance would start compounding
-- daily the moment it was entered — turning a good-faith migration into a
-- penalty. Landlord-overridable per balance for the case where the debt was
-- already accruing fees before the move.
--
-- Deliberately NOT reusing landlords.reconciliation_until: that window lets a
-- landlord mark a first GAM invoice paid off-platform (old autopay overlap) and
-- is time-boxed to onboarding. A carried balance is a debt that persists and
-- gets paid down over months. Different lifetime, different mechanism.
--
-- No backfill: existing invoices are engine-generated and none are carried
-- balances, so FALSE on both columns is correct for every current row.

ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS is_opening_balance boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS late_fee_exempt    boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN invoices.is_opening_balance IS
  'S605: a balance carried in from the landlord''s prior system, not generated by the billing engine.';
COMMENT ON COLUMN invoices.late_fee_exempt IS
  'S605: the nightly late-fee engine skips this invoice. Defaults TRUE on carried balances so migrated arrears do not start compounding; landlord may override per balance.';

-- The late-fee engine filters on it every night.
CREATE INDEX IF NOT EXISTS idx_invoices_late_fee_exempt
  ON invoices (lease_id) WHERE late_fee_exempt = true;

-- A carried balance is money earned BEFORE the platform. It must be payable and
-- must reconcile, but it is not GAM-era rent revenue and reporting it as rent
-- would overstate what the property earned while on GAM.
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_type_check;
ALTER TABLE payments ADD CONSTRAINT payments_type_check
  CHECK (type = ANY (ARRAY[
    'rent', 'fee', 'deposit', 'utility', 'float_fee', 'late_fee',
    'platform_fee', 'home_payment',
    'carried_balance'   -- S605: pre-platform arrears
  ]));
