#!/usr/bin/env bash
#
# Regenerate apps/api/src/db/schema.sql from the live dev database.
#
# Source of truth for SCHEMA CHANGES is apps/api/src/db/migrations/.
# This file is a flat snapshot for fast recon — "what columns does
# table X have right now?" — without replaying 80+ migrations.
#
# Hooked into migrate.ts (runs after a successful pending-migration
# apply) and exposed as `npm run db:dump-schema` for manual regen.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
API_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
OUT_FILE="$API_DIR/src/db/schema.sql"

DB_URL="${DATABASE_URL:-postgresql://postgres:gam_dev_password@localhost:5432/gam}"

HEADER='-- ============================================================
-- GAM DATABASE SCHEMA — AUTO-GENERATED SNAPSHOT
-- ============================================================
--
-- DO NOT EDIT THIS FILE.
--
-- This file is regenerated automatically after every successful
-- migration run by apps/api/src/db/migrate.ts. It is a flat
-- snapshot of the live dev database, produced by pg_dump.
--
-- Source of truth for SCHEMA CHANGES is the migrations directory:
--   apps/api/src/db/migrations/
--
-- This file is the source of truth for CURRENT STATE — useful for
-- answering "what columns does table X have right now?" without
-- replaying migrations in order.
--
-- To regenerate manually:  npm run db:dump-schema
-- ============================================================'

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

{
  printf '%s\n' "$HEADER"
  pg_dump \
    --schema-only \
    --no-owner \
    --no-privileges \
    "$DB_URL"
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUT_FILE"
echo "✓ schema.sql regenerated → $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
